server:
  port: 8080
kalah:
  default-pit-count: 6
  default-stone-count: 6
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


spring:
  mvc:
    view:
      prefix: /static
      suffix: .html